services:
  - type: web
    name: t3-clone
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: './bin/rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
  - type: worker
    name: solidqueue-worker
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails solid_queue:start"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mysite-db
          property: connectionString
databases:
  - name: mysite-db
    plan: free
